- hosts: all
  remote_user: root

  pre_tasks:
    - name: add host specific extra vars
      include_vars:
        file: /home/delfassy/projects/AnsibleRunnerForOvirtEngine/ansible-runner-service-project/env/289fc886-84f7-41ae-8059-ff11c062a366.yml

  roles:
    - name: role1
    - name: role2

  tasks:
    - name: test playbook, first task
      debug:
        msg: "this is a plain ansible task"

    - name: print an extra var
      debug:
        msg: "extra var cluster name: {{ host_deploy_cluster_name }}"

#    - name: aaa
#      task_test:
#        msg: "testing."

#    - name: test playbook, second task
#      debug:
#        msg: "this is a plain ansible task-2"
#---
#- name: my playbook
#  #hosts: ips
#  hosts: 192.168.100.204
#    #10.35.1.153
#    #[2001:db8:ca3:2:1::40]:128, 10.35.1.152:22
#  #         2001:db8:ca3:2:1::40
#  vars:
#    - bridge_type: OVS
#    - cpu_type: Intel Penryn Family
#    - ssh_config_path: '/etc/ssh/ssh_config'
#    - ssh_config_values: \tServerAliveInterval 240\n\tServerAliveCountMax 5
#  tasks:
#    - name: print ansible distribution version
#      debug:
#        msg: "this is a plain ansible task"
